apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: wordpress
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80        # Port exposed inside the cluster
      targetPort: 80  # Container's internal port
      nodePort: 30080 # The external port on each node (accessible from outside)
  type: NodePort 
