apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
stringData:
  MYSQL_USER: admin
  MYSQL_PASSWORD: cloud@1122
  MYSQL_DATABASE: database
  MYSQL_ROOT_PASSWORD: login

