apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual

